using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace PFE.application.DTOs
{
    public class ReportDto
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public DateTime SubmissionDate { get; set; }
        public DateTime? DueDate { get; set; }
        public bool IsSubmitted { get; set; }
        public bool IsApproved { get; set; }
        public bool IsRejected { get; set; }
        public string FeedbackComments { get; set; }
        public string Status { get; set; }

        // Informations du type de rapport
        public int ReportTypeId { get; set; }
        public string ReportTypeName { get; set; }
        public string ReportTypeDescription { get; set; }
        public string ReportTypeIconClass { get; set; }
        public string ReportTypeColor { get; set; }
        public bool IsAutoGenerated { get; set; }

        // Informations du stagiaire
        public int StagiaireId { get; set; }
        public string StagiaireName { get; set; }

        // Informations de l'approbateur
        public int? ApproverId { get; set; }
        public string ApproverName { get; set; }

        public string DownloadUrl { get; set; }
        public DateTime CreatedAt { get; set; }
        public DateTime? UpdatedAt { get; set; }
    }
}
