using System;

namespace PFE.Application.DTOs
{
    public class ReportTypeDto
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int DisplayOrder { get; set; }
        public int DaysFromStart { get; set; }
        public bool IsAutoGenerated { get; set; }
        public bool IsActive { get; set; }
        public string IconClass { get; set; }
        public string Color { get; set; }
        public DateTime CreatedAt { get; set; }
        public DateTime? UpdatedAt { get; set; }
    }

    public class CreateReportTypeDto
    {
        public string Name { get; set; }
        public string Description { get; set; }
        public int DisplayOrder { get; set; }
        public int DaysFromStart { get; set; }
        public bool IsAutoGenerated { get; set; } = false;
        public bool IsActive { get; set; } = true;
        public string IconClass { get; set; } = "fa-file";
        public string Color { get; set; } = "#007bff";
    }

    public class UpdateReportTypeDto
    {
        public string Name { get; set; }
        public string Description { get; set; }
        public int DisplayOrder { get; set; }
        public int DaysFromStart { get; set; }
        public bool IsAutoGenerated { get; set; }
        public bool IsActive { get; set; }
        public string IconClass { get; set; }
        public string Color { get; set; }
    }
}