// PFE.domain.Entities/ReportType.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace PFE.domain.Entities
{
    public class ReportType
    {
        [Key]
        public int Id { get; set; }

        [Required]
        [StringLength(100)]
        public string Name { get; set; }

        [StringLength(500)]
        public string Description { get; set; }

        /// <summary>
        /// Ordre d'affichage dans la timeline
        /// </summary>
        public int DisplayOrder { get; set; }

        /// <summary>
        /// Nombre de jours après le début du stage pour la date d'échéance
        /// </summary>
        public int DaysFromStart { get; set; }

        /// <summary>
        /// Indique si ce rapport est généré automatiquement
        /// </summary>
        public bool IsAutoGenerated { get; set; } = false;

        /// <summary>
        /// Indique si ce type de rapport est actif
        /// </summary>
        public bool IsActive { get; set; } = true;

        /// <summary>
        /// Icône FontAwesome pour l'affichage
        /// </summary>
        [StringLength(50)]
        public string IconClass { get; set; } = "fa-file";

        /// <summary>
        /// Couleur hexadécimale pour l'affichage
        /// </summary>
        [StringLength(7)]
        public string Color { get; set; } = "#007bff";

        /// <summary>
        /// Date de création
        /// </summary>
        public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

        /// <summary>
        /// Date de dernière modification
        /// </summary>
        public DateTime? UpdatedAt { get; set; }

        /// <summary>
        /// Navigation property vers les rapports
        /// </summary>
        public virtual ICollection<Report> Reports { get; set; } = new List<Report>();
    }
}